%cross correlation of signal and sequences
clc;
clear all;
close all;
t=-10:0.1:10;
x1=sin(2*pi*t);
subplot(4,1,1);
plot(t,x1);
xlabel('t');
ylabel('x1');
title('sine');
x2=exp(t);
subplot(4,1,2);
plot(t,x2);
xlabel('t');
ylabel('x2');
title('exponential');
y=xcorr(x1,x2);
subplot(4,1,3);
plot(y);
xlabel('t');
ylabel('y(t)');
title('cross correlation');
y1=xcorr(x1,x1);
subplot(4,1,4);
plot(y1);
xlabel('t');
ylabel('y1(t)');
title('auto correlation');
figure;
